### ISSUE TITLE
[Bug] Gboard and back gesture aren't working with turned on app

### ISSUE THREAD

**Issue by untd0** [Angel-Studio/MaterialYou-Dynamic-Island#17]
**Describe the bug**
Gboard and back gesture isn't working with turned on app

**To Reproduce**
1. Go to the app and turn on overlay and accessibility permission 
2. Try to input someting somewhere
3. See that keyboard isn't opening and back gesture working not every time

**Expected behavior**
Keyboard opens and gesture is working properly 

**Screenshots**
![Screenshot_20230411-214621](https://user-images.githubusercontent.com/64734226/231233044-6ade7450-a979-4f16-b65b-29c6afa43172.png)

**Smartphone:**
 - Device: Pixel 6
 - OS: Android 13 (T3B2.230316.005)
 - Version of app: 1.0.4

**Comment by JulesPvx** [comment]
Fixed in 1.0.5-alpha

**Comment by JulesPvx** [comment]
ty :)
